spring:
  application:
    name: Notification-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: order_service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://schema-registry:8085
        specific.avro.reader: true
        spring.json.trusted.packages: "*"

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8083
